version: 2

project:
  name: "meka-filesystem"
  description: "MCP remoto para el manejo de archivos"
  type: generic
  objective: "un servidor MCP para el manejo de archivos"
  agent: null
  owner: null
  domain: null

status:
  active: true
  exposed: false
  archived: false

metadata:
  template: project-v2
  template_version: 2
